version: '3.8'

services:

  postgres-fastapi:
    image: postgres:14.5
    expose:
      - 5432
    restart: always
    env_file:
      - ./.env

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    depends_on:
      - postgres-fastapi

  backend:
    build: .
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8080"
    ports:
      - 8080:8080
    volumes:
      - ./files:/code/files/
    env_file:
      - ./.env
    depends_on:
      - redis

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./services/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

    depends_on:
      - backend